# Generated by Django 5.0.4 on 2024-05-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
        ('cuentas', '0004_alter_cuenta_avion'),
        ('tienda', '0002_avion_descripcion_alter_stockavion_cantidad_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoproducto',
            name='avion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='aviones.avion'),
        ),
        migrations.AlterField(
            model_name='movimientoproducto',
            name='avion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='aviones.avion'),
        ),
        migrations.AlterField(
            model_name='stockavion',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion'),
        ),
        migrations.DeleteModel(
            name='Avion',
        ),
    ]
