# Generated by Django 5.0.4 on 2024-06-04 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
        ('tienda', '0004_alter_stockavion_cantidad_minima_orden_ordenproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('MO', 'Movimiento por Orden'), ('AS', 'Ajuste Stock'), ('MP', 'Movimiento Producto')], max_length=2)),
                ('observacion', models.CharField(max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
