# Generated by Django 5.0.4 on 2024-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
