# Generated by Django 5.0.4 on 2024-05-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_avion_descripcion'),
        ('tienda', '0002_avion_descripcion_alter_stockavion_cantidad_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='avion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.avion'),
        ),
        migrations.DeleteModel(
            name='Avion',
        ),
    ]
