# Generated by Django 5.0.4 on 2024-05-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
        ('cuentas', '0003_alter_cuenta_avion_delete_avion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='avion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviones.avion'),
        ),
    ]
