# Generated by Django 5.0.4 on 2024-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_cuenta_avion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='es_tripulante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
